name: solar system workflow

on:
  workflow_dispatch:
  push:
    branches:
      - feature-branch
      - main

env:
  MONGO_URI: ${{ vars.MONGO_URL }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-test:
    name: unit testing
    strategy:
      matrix:
        node-version: [18,19,20]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - node-version: 18
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: set up nodesJs version - ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependences
        run: npm install

      - name: unit testing
        id: NodeJs-unit-testing-step
        run: npm test

      - name: Archive test results
        if: steps.NodeJs-unit-testing-step.outcome == 'failure' || steps.NodeJs-unit-testing-step.outcome == 'success'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: 'artifact ${{ matrix.os }}-${{ matrix.node-version }} '
          path: test-results.xml
